### ISSUE TITLE
How to output a Tiff file during prediction

### ISSUE THREAD

**Issue by aloma85** [juglab/PPN2V#6]
I trained the model with a .tif file and I'm looking to have the denoise file be a tiff file as well with all its layers.

plt.imsave('../../../imgs/PN2V_BootHist.png', mseEst[100:200,150:250])

This saves the image as a single .png file. How do I save it as the full .tif movie?

**Comment by lmanan** [comment]
Hello @aloma85 

Thank you for looking through `PPN2V`.
We append the PPN2V denoised prediction in the list `resultImgs` in the notebook `*/PN2V/3_ProbabilisticNoise2VoidPrediction.ipynb`

One could save that variable, like with the following code:

```python
from tifffile import imsave
imsave('../../../imgs/PN2V_BootHist.tif', resultImgs)
# Specify data type like below, if you would like to open `PN2V_BootHist.tif` in the `Fiji` software, for example
# imsave('../../../imgs/PN2V_BootHist.tif', resultImgs.astype(np.uint16))
```

Does that help?

**Comment by aloma85** [comment]
Thanks you, it does. Another related question though. Do I make any changes to the training process with .tif file frames? Because my training results were horrid

**Comment by lmanan** [comment]
Thank you for the comment!

Could you share some information about your images, for example, what is the typical intensity range of the noisy images (obtainable through `np.min(im)` and `np.max(im)`, where `im` is the numpy array corresponding to the noisy images), are they 8 bit/16 bit etc?

Without knowing the specifics of your data, I would direct you to to the  `min_sigma` parameter which is used while creating the bootstrapped noise model in the notebook file `PN2V/1b_CreateNoiseModel_Bootstrap.ipynb`. The final parameter `min_sigma` could be lowered from a default value of 50, maybe that helps? (we set it to 50 for numerical stability purposes but this could be a tad too high if the intensity range of the noisy images is on the lower spectrum,  to begin with ...)

```python3
gaussianMixtureNoiseModel = pn2v.gaussianMixtureNoiseModel.GaussianMixtureNoiseModel(min_signal = min_signal,
max_signal = max_signal, path=path, weight = None, 
n_gaussian = n_gaussian, n_coeff = n_coeff, device = device, min_sigma = 50)
```

Another option you could try is varying the number of gaussians (`n_gaussian`) which are used to create the gaussian mixture noise model. This variable is set to 3 by default (we chose 3 because it provided the most robust results across the three datasets we investigated in our publication), but maybe trying a fewer number of gaussians (1or 2) helps?

```python3
n_gaussian = 3 # Number of gaussians to use for Gaussian Mixture Model
n_coeff = 2 # No. of polynomial coefficients for parameterizing the mean, standard deviation and weight of Gaussian components.
```

**Comment by aloma85** [comment]
The intensity range for the 16bit tiff file is 0 to 65535. I'm also looking to train the Histogram Noise Model as opposed to the GMM. Thanks

**Comment by lmanan** [comment]
Closing this issue. Please feel free to re-open if there are more questions.
